pull_request_rules:
  - name: backport to humble at reviewers discretion
    conditions:
      - base=main
      - "label=backport-humble"
    actions:
      backport:
        branches:
          - humble
        labels:
          - humble
        title: Backport of {{ title }} (#{{ number }})

  - name: ask to resolve conflict
    conditions:
      - conflict
      - author!=mergify
    actions:
        comment:
          message: This pull request is in conflict. Could you fix it @{{author}}?
